valor = int(input('Digite um valor para ser multiplicado: '))
valorx1 = valor * 1
valorx2 = valor * 2
valorx3 = valor * 3
valorx4 = valor * 4
valorx5 = valor * 5
valorx6 = valor * 6
valorx7 = valor * 7
valorx8 = valor * 8
valorx9 = valor * 9
valorx10 = valor * 10
print(f"{valor} x 1 = ", valorx1)
print(f"{valor} x 2 = ", valorx2)
print(f"{valor} x 3 = ", valorx3)
print(f"{valor} x 3 = ", valorx4)
print(f'{valor} x 5 = ', valorx5)
print(f"{valor} x 6 = ", valorx6)
print(f"{valor} x 7 = ", valorx7)
print(f"{valor} x 8 = ", valorx8)
print(f"{valor} x 9 = ", valorx9)
print(f"{valor} x 10 = ", valorx10)